name: Node Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build:prod
      - run: npm run test:unit
        env:
          do_endpoint: ${{ secrets.do_endpoint }}
          do_secretAccessKey: ${{ secrets.do_secretAccessKey }}
          do_accessKeyId: ${{ secrets.do_accessKeyId }}
          do_bucket: ${{ secrets.do_bucket }}
          APPDATA: appdata
